FROM node:latest

WORKDIR /express-es2017-starter

# install packages
COPY package*.json ./
RUN npm set progress=false && npm install --production

# copy server files
COPY src src

EXPOSE 8080

CMD [ "npm", "start" ]
